In [291]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [292]:
#cargar archivo csv desde seaborn
#Convertir en dataframe
df_sydney= pd.read_csv("mexico_limpio.csv")
df_sydney.head(5)

Unnamed: 0  host_listings_count  host_total_listings_count  latitude  \
0           0                  3.0                        6.0  19.42063   
1           1                  1.0                        1.0  19.38283   
2           2                 17.0                       17.0  19.41162   
3           3                  1.0                        4.0  19.43956   
4           4                  3.0                        4.0  19.41152   

   longitude  accommodates  bathrooms  bedrooms  beds   price  ...  \
0  -99.16586           2.0        1.0       1.0   2.0  1652.0  ...   
1  -99.20000           2.0        1.0       1.0   1.0  3663.0  ...   
2  -99.17794           3.1        1.4       5.0   1.8  1314.4  ...   
3  -99.17263           4.0        1.0       2.0   3.0   814.0  ...   
4  -99.16857           4.0        1.0       2.0   2.0  1923.0  ...   

         room_type  bathrooms_text  \
0  Entire home/apt          1 bath   
1  Entire home/apt          1 bath   
2  Entire home/apt       5.5 baths   
3  Entire home/apt          1 bath   
4  Entire home/apt          1 bath   

                                           amenities  calendar_updated  \
0  ["40 inch HDTV with Amazon Prime Video, Netfli...             nulos   
1  ["Hot water", "Washer", "Bed linens", "Wifi", ...             nulos   
2  ["Wifi", "Coffee maker: Nespresso", "Host gree...             nulos   
3  ["Wifi", "Host greets you", "Coffee maker", "S...             nulos   
4  ["Wifi", "Coffee maker", "Sound system", "Clot...             nulos   

   has_availability  calendar_last_scraped  first_review  last_review  \
0                 t             2024-06-28    2013-03-30   2024-04-17   
1                 t             2024-06-27    2013-03-30   2024-04-17   
2                 t             2024-06-28    2011-11-09   2023-03-26   
3                 t             2024-06-28    2013-05-16   2024-05-21   
4                 t             2024-06-28    2011-11-17   2024-05-05   

   license  instant_bookable  
0    nulos                 f  
1    nulos                 f  
2    nulos                 f  
3    nulos                 t  
4    nulos                 f  

[5 rows x 112 columns]

In [293]:
df_sydney.isnull().sum()

Unnamed: 0                   0
host_listings_count          0
host_total_listings_count    0
latitude                     0
longitude                    0
                            ..
calendar_last_scraped        0
first_review                 0
last_review                  0
license                      0
instant_bookable             0
Length: 112, dtype: int64

In [294]:
#df_sydney.info()

***Creación de Categorias a partir de clases***

In [295]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['price'].max()
Min=df_sydney['price'].min()
Limites= [Min, Max]
Limites

[105.0, 13283.0]

In [296]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(104, 13284, 3)
intervalos

array([  104.,  6694., 13284.])

In [297]:
#Creamos las categorías 
categorias= ["cheap", "expensive"]

In [298]:
price_numerico=df_sydney["price"]
df_sydney.insert(0,"price_numerico",price_numerico)

In [299]:
#Finalmente creamos las categorías en la columna numérica
df_sydney['price']=pd.cut(x= df_sydney['price'], bins=intervalos, labels= categorias )

In [300]:
df_sydney['price'].head()

0    cheap
1    cheap
2    cheap
3    cheap
4    cheap
Name: price, dtype: category
Categories (2, object): ['cheap' < 'expensive']

In [301]:
df_sydney["price"].isnull().sum()

0

***Modelo 1***

In [302]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df_sydney[['accommodates']]
Var_Dep= df_sydney['price']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="cheap")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="expensive")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="cheap")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="expensive")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[7866    0]
 [  95    0]]
Precisión del modelo:
0.9880668257756563
Precisión del modelo:
0.0
Exactitud del modelo:
0.9880668257756563
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 2***

In [303]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['host_total_listings_count'].max()
Min=df_sydney['host_total_listings_count'].min()
Limites= [Min, Max]
Limites

[1.0, 442.0]

In [304]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(0, 443, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['host_total_listings_count']
df_sydney.insert(0,"host_total_listings_count_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['host_total_listings_count']=pd.cut(x= df_sydney['host_total_listings_count'], bins=intervalos, labels= categorias )

df_sydney['host_total_listings_count'].head()

df_sydney["host_total_listings_count"].isnull().sum()


0

In [305]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df_sydney[['accommodates']]
Var_Dep= df_sydney['host_total_listings_count']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[7790    0]
 [ 171    0]]
Precisión del modelo:
0.9785202863961814
Precisión del modelo:
0.0
Exactitud del modelo:
0.9785202863961814
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 3***

In [306]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['reviews_per_month'].max()
Min=df_sydney['reviews_per_month'].min()
Limites= [Min, Max]
Limites

[0.01, 7.43]

In [307]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(0, 7.44, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['reviews_per_month']
df_sydney.insert(0,"reviews_per_month_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['reviews_per_month']=pd.cut(x= df_sydney['reviews_per_month'], bins=intervalos, labels= categorias )

df_sydney['reviews_per_month'].head()

df_sydney["reviews_per_month"].isnull().sum()

0

In [308]:
df_sydney['host_response_rate'] = df_sydney['host_response_rate'].str.rstrip('%')  # Elimina el %
df_sydney['host_response_rate'] = pd.to_numeric(df_sydney['host_response_rate'])   # Convierte a numérico


In [309]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df_sydney[['host_response_rate']]
Var_Dep= df_sydney['reviews_per_month']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[7183    0]
 [ 778    0]]
Precisión del modelo:
0.9022735837206382
Precisión del modelo:
0.0
Exactitud del modelo:
0.9022735837206382
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 4***

In [310]:
unico = np.unique(df_sydney["property_type"])
unico

array(['Boat', 'Campsite', 'Casa particular', 'Castle', 'Dome',
       'Earthen home', 'Entire bungalow', 'Entire cabin', 'Entire chalet',
       'Entire condo', 'Entire cottage', 'Entire guest suite',
       'Entire guesthouse', 'Entire home', 'Entire home/apt',
       'Entire hostel', 'Entire in-law', 'Entire loft', 'Entire place',
       'Entire rental unit', 'Entire serviced apartment',
       'Entire townhouse', 'Entire vacation home', 'Entire villa',
       'Farm stay', 'Holiday park', 'Hut', 'Private room',
       'Private room in barn', 'Private room in bed and breakfast',
       'Private room in bungalow', 'Private room in cabin',
       'Private room in casa particular', 'Private room in castle',
       'Private room in chalet', 'Private room in condo',
       'Private room in cottage', 'Private room in dome',
       'Private room in dorm', 'Private room in earthen home',
       'Private room in farm stay', 'Private room in floor',
       'Private room in guest suite', 'Priva

In [311]:
df_sydney["property_type"]=df_sydney["property_type"].replace(['Boat', 'Campsite', 'Casa particular', 'Castle', 'Dome',
       'Earthen home', 'Entire bungalow', 'Entire cabin', 'Entire chalet',
       'Entire condo', 'Entire cottage', 'Entire guest suite',
       'Entire guesthouse', 'Entire home', 'Entire home/apt',
       'Entire hostel', 'Entire in-law', 'Entire loft', 'Entire place',
       'Entire rental unit', 'Entire serviced apartment',
       'Entire townhouse', 'Entire vacation home', 'Entire villa',
       'Farm stay', 'Holiday park', 'Hut', 'Private room',
       'Private room in barn', 'Private room in bed and breakfast',
       'Private room in bungalow', 'Private room in cabin',
       'Private room in casa particular', 'Private room in castle',
       'Private room in chalet', 'Private room in condo',
       'Private room in cottage', 'Private room in dome',
       'Private room in dorm', 'Private room in earthen home',
       'Private room in farm stay', 'Private room in floor',
       'Private room in guest suite', 'Private room in guesthouse',
       'Private room in home', 'Private room in hostel',
       'Private room in houseboat', 'Private room in hut',
       'Private room in lighthouse', 'Private room in loft',
       'Private room in minsu', 'Private room in nature lodge',],"grupo1")

In [312]:
df_sydney["property_type"]=df_sydney["property_type"].replace(['Private room in pension', 'Private room in rental unit',
       'Private room in resort', 'Private room in serviced apartment',
       'Private room in shipping container', 'Private room in tent',
       'Private room in tiny home', 'Private room in tower',
       'Private room in townhouse', 'Private room in vacation home',
       'Private room in villa', 'Room in aparthotel',
       'Room in bed and breakfast', 'Room in boutique hotel',
       'Room in casa particular', 'Room in hostel', 'Room in hotel',
       'Room in serviced apartment', 'Shared room',
       'Shared room in bed and breakfast',
       'Shared room in boutique hotel', 'Shared room in cabin',
       'Shared room in casa particular', 'Shared room in condo',
       'Shared room in dorm', 'Shared room in guest suite',
       'Shared room in guesthouse', 'Shared room in home',
       'Shared room in hostel', 'Shared room in hotel',
       'Shared room in loft', 'Shared room in rental unit',
       'Shared room in serviced apartment', 'Shared room in tent',
       'Shared room in tiny home', 'Shared room in townhouse',
       'Shared room in vacation home', 'Shipping container', 'Tent',
       'Tiny home', 'Tipi'],"grupo2")

In [313]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['host_response_rate']]
Var_Dep = df_sydney['property_type']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[6589    0]
 [1372    0]]
Precisión del modelo:
0.8276598417284261
Precisión del modelo:
0.0
Exactitud del modelo:
0.8276598417284261
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 5***

In [314]:
unico = np.unique(df_sydney["host_response_time"])
unico

array(['a few days or more', 'within a day', 'within a few hours',
       'within an hour'], dtype=object)

In [315]:
df_sydney["host_response_time"]=df_sydney["host_response_time"].replace(['a few days or more', 'within a day'],"grupo1")
df_sydney["host_response_time"]=df_sydney["host_response_time"].replace(['within a few hours','within an hour'],"grupo2")

In [316]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['price_numerico']]
Var_Dep = df_sydney['host_response_time']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[   0  696]
 [   0 7265]]
Precisión del modelo:
0.0
Precisión del modelo:
0.9125737972616506
Exactitud del modelo:
0.9125737972616506
Sensibilidad del modelo:
0.0
Sensibilidad del modelo:
1.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 6***

In [317]:
unico = np.unique(df_sydney["host_is_superhost"])
unico

array(['f', 't'], dtype=object)

In [318]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['review_scores_communication']]
Var_Dep = df_sydney['host_is_superhost']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="t")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[4732    0]
 [3229    0]]
Precisión del modelo:
0.5943976887325713
Precisión del modelo:
0.0
Exactitud del modelo:
0.5943976887325713
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 7***

In [319]:
unico = np.unique(df_sydney["maximum_nights"])
unico

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   42,   43,   44,   45,
         46,   48,   49,   50,   52,   55,   56,   57,   58,   59,   60,
         61,   62,   63,   64,   65,   69,   70,   71,   75,   80,   82,
         83,   84,   85,   88,   89,   90,   91,   92,   93,   94,   95,
         96,   99,  100,  102,  112,  114,  115,  118,  119,  120,  122,
        125,  130,  135,  137,  140,  141,  150,  152,  160,  168,  170,
        174,  175,  179,  180,  181,  182,  183,  184,  185,  186,  187,
        188,  190,  193,  197,  199,  200,  210,  212,  220,  221,  238,
        240,  250,  254,  255,  260,  265,  280,  290,  300,  301,  309,
        320,  322,  325,  330,  340,  345,  350,  354,  355,  356,  358,
        359,  360,  362,  363,  364,  365,  366,  3

In [320]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['maximum_nights'].max()
Min=df_sydney['maximum_nights'].min()
Limites= [Min, Max]
Limites

[1, 1825]

In [321]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(0, 1826, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['maximum_nights']
df_sydney.insert(0,"maximum_nights_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['maximum_nights']=pd.cut(x= df_sydney['maximum_nights'], bins=intervalos, labels= categorias )

df_sydney['maximum_nights'].head()

df_sydney["maximum_nights"].isnull().sum()

0

In [322]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['minimum_nights']]
Var_Dep = df_sydney['maximum_nights']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[5296   12]
 [2650    3]]
Precisión del modelo:
0.6664988673546438
Precisión del modelo:
0.2
Exactitud del modelo:
0.6656198969978646
Sensibilidad del modelo:
0.9977392614920875
Sensibilidad del modelo:
0.0011307953260459858


***Modelo 8***

In [323]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['bathrooms'].max()
Min=df_sydney['bathrooms'].min()
Limites= [Min, Max]
Limites

[0.0, 4.5]

In [324]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(-1, 4.6, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['bathrooms']
df_sydney.insert(0,"bathrooms_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['bathrooms']=pd.cut(x= df_sydney['bathrooms'], bins=intervalos, labels= categorias )

df_sydney['bathrooms'].head()

df_sydney["bathrooms"].isnull().sum()

0

In [325]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['bedrooms']]
Var_Dep = df_sydney['bathrooms']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[5534  170]
 [1661  596]]
Precisión del modelo:
0.7691452397498263
Precisión del modelo:
0.7780678851174935
Exactitud del modelo:
0.7700037683708076
Sensibilidad del modelo:
0.9701963534361852
Sensibilidad del modelo:
0.26406734603455917


***Modelo 9***

In [326]:
df_sydney.columns

Index(['bathrooms_numeric', 'maximum_nights_numeric',
       'reviews_per_month_numeric', 'host_total_listings_count_numeric',
       'price_numerico', 'Unnamed: 0', 'host_listings_count',
       'host_total_listings_count', 'latitude', 'longitude',
       ...
       'room_type', 'bathrooms_text', 'amenities', 'calendar_updated',
       'has_availability', 'calendar_last_scraped', 'first_review',
       'last_review', 'license', 'instant_bookable'],
      dtype='object', length=117)

In [327]:
unico = np.unique(df_sydney["room_type"])
unico

array(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
      dtype=object)

In [328]:
df_sydney["room_type"]=df_sydney["room_type"].replace(['Hotel room', 'Entire home/apt'],"grupo1")
df_sydney["room_type"]=df_sydney["room_type"].replace(['Shared room',"Private room"],"grupo2")

In [329]:
unico = np.unique(df_sydney["room_type"])
unico

array(['grupo1', 'grupo2'], dtype=object)

In [330]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['price_numerico']]
Var_Dep = df_sydney['room_type']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[5064  148]
 [1911  838]]
Precisión del modelo:
0.7260215053763441
Precisión del modelo:
0.8498985801217038
Exactitud del modelo:
0.7413641502323829
Sensibilidad del modelo:
0.9716039907904835
Sensibilidad del modelo:
0.30483812295380136


***Modelo 10***

In [331]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['review_scores_location'].max()
Min=df_sydney['review_scores_location'].min()
Limites= [Min, Max]
Limites

[3.97, 5.0]

In [332]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(3.96, 5.1, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['review_scores_location']
df_sydney.insert(0,"review_scores_location_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['review_scores_location']=pd.cut(x= df_sydney['review_scores_location'], bins=intervalos, labels= categorias )

df_sydney['review_scores_location'].head()

df_sydney["review_scores_location"].isnull().sum()

0

In [333]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['availability_30']]
Var_Dep = df_sydney['review_scores_location']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[   0  496]
 [   0 7465]]
Precisión del modelo:
0.0
Precisión del modelo:
0.9376962693129004
Exactitud del modelo:
0.9376962693129004
Sensibilidad del modelo:
0.0
Sensibilidad del modelo:
1.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
