In [251]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [252]:
#cargar archivo csv desde seaborn
#Convertir en dataframe
df_sydney= pd.read_csv("Sydney.csv")
df_sydney.head(5)

Unnamed: 0  host_response_time  host_acceptance_rate         property_type  \
0           0  within a few hours                     0    Entire rental unit   
1           1  within a few hours                   100  Private room in home   
2           2      within an hour                   100    Entire rental unit   
3           3  within a few hours                   100  Private room in home   
4           4  within a few hours                    94    Entire rental unit   

         room_type                                          amenities  \
0  Entire home/apt  ["Essentials", "Heating", "TV with standard ca...   
1     Private room  ["Fire extinguisher", "Outdoor furniture", "Sh...   
2  Entire home/apt  ["Fire extinguisher", "Outdoor furniture", "Ro...   
3     Private room  ["Fire extinguisher", "Bed linens", "Indoor fi...   
4  Entire home/apt  ["Essentials", "Microwave", "Heating", "Stove"...   

  host_is_superhost  host_response_rate  host_acceptance_rate.1  \
0                 f               100.0                    89.6   
1                 t               100.0                   100.0   
2                 t               100.0                   100.0   
3                 t               100.0                   100.0   
4                 t               100.0                    94.0   

   host_listings_count  ...  review_scores_cleanliness  review_scores_checkin  \
0                  1.0  ...                       4.92                   4.97   
1                  3.0  ...                       4.92                   4.97   
2                  1.0  ...                       4.86                   4.97   
3                  3.0  ...                       4.81                   4.92   
4                  2.0  ...                       4.91                   4.95   

   review_scores_communication  review_scores_location  review_scores_value  \
0                         4.97                    4.87                 4.90   
1                         4.97                    4.87                 4.90   
2                         4.94                    4.92                 4.72   
3                         5.00                    4.81                 4.86   
4                         5.00                    4.98                 4.93   

   calculated_host_listings_count  \
0                             1.0   
1                             2.0   
2                             1.0   
3                             2.0   
4                             1.0   

   calculated_host_listings_count_entire_homes  \
0                                          1.0   
1                                          0.0   
2                                          1.0   
3                                          0.0   
4                                          1.0   

   calculated_host_listings_count_private_rooms  \
0                                           0.0   
1                                           2.0   
2                                           0.0   
3                                           2.0   
4                                           0.0   

   calculated_host_listings_count_shared_rooms  reviews_per_month  
0                                          0.0               0.94  
1                                          0.0               0.94  
2                                          0.0               3.03  
3                                          0.0               0.36  
4                                          0.0               0.62  

[5 rows x 45 columns]

In [253]:
#df_sydney.isnull().sum()

In [254]:
#df_sydney.info()

***Creación de Categorias a partir de clases***

In [255]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['price'].max()
Min=df_sydney['price'].min()
Limites= [Min, Max]
Limites

[16.0, 792.0]

In [256]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(15, 793, 3)
intervalos

array([ 15., 404., 793.])

In [257]:
#Creamos las categorías 
categorias= ["cheap", "expensive"]

In [258]:
price_numerico=df_sydney["price"]
df_sydney.insert(0,"price_numerico",price_numerico)

In [259]:
#Finalmente creamos las categorías en la columna numérica
df_sydney['price']=pd.cut(x= df_sydney['price'], bins=intervalos, labels= categorias )

In [260]:
df_sydney['price'].head()

0        cheap
1        cheap
2        cheap
3        cheap
4    expensive
Name: price, dtype: category
Categories (2, object): ['cheap' < 'expensive']

In [261]:
df_sydney["price"].isnull().sum()

0

***Modelo 1***

In [262]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df_sydney[['accommodates']]
Var_Dep= df_sydney['price']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="cheap")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="expensive")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="cheap")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="expensive")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[4098   12]
 [ 550    5]]
Precisión del modelo:
0.8816695352839932
Precisión del modelo:
0.29411764705882354
Exactitud del modelo:
0.8795284030010718
Sensibilidad del modelo:
0.997080291970803
Sensibilidad del modelo:
0.009009009009009009


***Modelo 2***

In [263]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['host_total_listings_count'].max()
Min=df_sydney['host_total_listings_count'].min()
Limites= [Min, Max]
Limites

#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(-1, 466, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['host_total_listings_count']
df_sydney.insert(0,"host_total_listings_count_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['host_total_listings_count']=pd.cut(x= df_sydney['host_total_listings_count'], bins=intervalos, labels= categorias )

df_sydney['host_total_listings_count'].head()

df_sydney["host_total_listings_count"].isnull().sum()


0

In [264]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df_sydney[['accommodates']]
Var_Dep= df_sydney['host_total_listings_count']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[4556    0]
 [ 109    0]]
Precisión del modelo:
0.9766345123258307
Precisión del modelo:
0.0
Exactitud del modelo:
0.9766345123258307
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 3***

In [265]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['reviews_per_month'].max()
Min=df_sydney['reviews_per_month'].min()
Limites= [Min, Max]
Limites

#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(0, 5.79, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['reviews_per_month']
df_sydney.insert(0,"reviews_per_month_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['reviews_per_month']=pd.cut(x= df_sydney['reviews_per_month'], bins=intervalos, labels= categorias )

df_sydney['reviews_per_month'].head()

df_sydney["reviews_per_month"].isnull().sum()

0

In [266]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df_sydney[['host_response_rate']]
Var_Dep= df_sydney['reviews_per_month']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[4051    0]
 [ 614    0]]
Precisión del modelo:
0.8683815648445874
Precisión del modelo:
0.0
Exactitud del modelo:
0.8683815648445874
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 4***

In [267]:
unico = np.unique(df_sydney["property_type"])
unico

array(['Barn', 'Boat', 'Camper/RV', 'Campsite', 'Casa particular', 'Dome',
       'Earthen home', 'Entire bungalow', 'Entire cabin', 'Entire condo',
       'Entire cottage', 'Entire guest suite', 'Entire guesthouse',
       'Entire home', 'Entire home/apt', 'Entire loft', 'Entire place',
       'Entire rental unit', 'Entire serviced apartment',
       'Entire townhouse', 'Entire vacation home', 'Entire villa',
       'Farm stay', 'Holiday park', 'Houseboat', 'Hut', 'Island',
       'Private room', 'Private room in bed and breakfast',
       'Private room in bungalow', 'Private room in cabin',
       'Private room in camper/rv', 'Private room in casa particular',
       'Private room in chalet', 'Private room in condo',
       'Private room in cottage', 'Private room in earthen home',
       'Private room in guest suite', 'Private room in guesthouse',
       'Private room in home', 'Private room in hostel',
       'Private room in loft', 'Private room in minsu',
       'Private room in 

In [268]:
df_sydney["property_type"]=df_sydney["property_type"].replace(['Barn', 'Boat', 'Camper/RV', 'Campsite', 'Casa particular', 'Dome',
       'Earthen home', 'Entire bungalow', 'Entire cabin', 'Entire condo',
       'Entire cottage', 'Entire guest suite', 'Entire guesthouse',
       'Entire home', 'Entire home/apt', 'Entire loft', 'Entire place',
       'Entire rental unit', 'Entire serviced apartment',
       'Entire townhouse', 'Entire vacation home', 'Entire villa',
       'Farm stay', 'Holiday park', 'Houseboat', 'Hut', 'Island',
       'Private room', 'Private room in bed and breakfast',
       'Private room in bungalow', 'Private room in cabin',
       'Private room in camper/rv', 'Private room in casa particular',
       'Private room in chalet', 'Private room in condo',
       'Private room in cottage', 'Private room in earthen home',
       'Private room in guest suite', 'Private room in guesthouse',
       'Private room in home'],"grupo1")

In [269]:
df_sydney["property_type"]=df_sydney["property_type"].replace(['Private room in hostel',
       'Private room in loft', 'Private room in minsu',
       'Private room in rental unit', 'Private room in resort',
       'Private room in serviced apartment', 'Private room in tiny home',
       'Private room in townhouse', 'Private room in treehouse',
       'Private room in vacation home', 'Private room in villa',
       'Private room in yurt', 'Room in aparthotel',
       'Room in boutique hotel', 'Room in hotel',
       'Room in serviced apartment', 'Shared room',
       'Shared room in bed and breakfast',
       'Shared room in boutique hotel', 'Shared room in condo',
       'Shared room in guesthouse', 'Shared room in home',
       'Shared room in hostel', 'Shared room in rental unit',
       'Shared room in townhouse', 'Shared room in villa', 'Tent',
       'Tiny home', 'Train', 'Treehouse'],"grupo2")

In [270]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['host_response_rate']]
Var_Dep = df_sydney['property_type']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[4218    0]
 [ 447    0]]
Precisión del modelo:
0.9041800643086817
Precisión del modelo:
0.0
Exactitud del modelo:
0.9041800643086817
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 5***

In [271]:
unico = np.unique(df_sydney["host_response_time"])
unico

array(['a few days or more', 'within a day', 'within a few hours',
       'within an hour'], dtype=object)

In [274]:
df_sydney["host_response_time"]=df_sydney["host_response_time"].replace(['a few days or more', 'within a day'],"grupo1")
df_sydney["host_response_time"]=df_sydney["host_response_time"].replace(['within a few hours','within an hour'],"grupo2")

In [275]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['price_numerico']]
Var_Dep = df_sydney['host_response_time']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[4199    0]
 [ 466    0]]
Precisión del modelo:
0.9001071811361201
Precisión del modelo:
0.0
Exactitud del modelo:
0.9001071811361201
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 6***

In [276]:
unico = np.unique(df_sydney["host_is_superhost"])
unico

array(['f', 't'], dtype=object)

In [277]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['review_scores_communication']]
Var_Dep = df_sydney['host_is_superhost']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="t")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="t")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[3215    0]
 [1450    0]]
Precisión del modelo:
0.6891747052518756
Precisión del modelo:
0.0
Exactitud del modelo:
0.6891747052518756
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 7***

In [282]:
unico = np.unique(df_sydney["maximum_nights"])
unico

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   40,   42,   43,   44,   45,   46,
         47,   48,   49,   50,   51,   52,   55,   56,   57,   58,   59,
         60,   61,   62,   63,   65,   68,   70,   71,   73,   74,   75,
         80,   84,   85,   87,   88,   89,   90,   91,   92,   93,   95,
         97,   98,   99,  100,  110,  112,  113,  119,  120,  123,  124,
        125,  130,  138,  140,  150,  152,  154,  155,  156,  160,  165,
        167,  170,  175,  176,  177,  178,  180,  181,  182,  183,  185,
        186,  188,  190,  194,  200,  201,  206,  210,  218,  220,  240,
        250,  255,  260,  265,  270,  280,  299,  300,  305,  309,  316,
        320,  325,  330,  334,  335,  336,  350,  352,  354,  355,  356,
        358,  360,  362,  363,  364,  365,  366,  3

In [284]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['maximum_nights'].max()
Min=df_sydney['maximum_nights'].min()
Limites= [Min, Max]
Limites

#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(0, 1163, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['maximum_nights']
df_sydney.insert(0,"maximum_nights_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['maximum_nights']=pd.cut(x= df_sydney['maximum_nights'], bins=intervalos, labels= categorias )

df_sydney['maximum_nights'].head()

df_sydney["maximum_nights"].isnull().sum()

0

In [285]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['minimum_nights']]
Var_Dep = df_sydney['maximum_nights']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[3062  237]
 [ 963  403]]
Precisión del modelo:
0.7607453416149068
Precisión del modelo:
0.6296875
Exactitud del modelo:
0.7427652733118971
Sensibilidad del modelo:
0.9281600484995454
Sensibilidad del modelo:


***Modelo 8***

In [287]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['bathrooms'].max()
Min=df_sydney['bathrooms'].min()
Limites= [Min, Max]
Limites

#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(-1, 4, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['bathrooms']
df_sydney.insert(0,"bathrooms_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['bathrooms']=pd.cut(x= df_sydney['bathrooms'], bins=intervalos, labels= categorias )

df_sydney['bathrooms'].head()

df_sydney["bathrooms"].isnull().sum()

0

In [288]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['bedrooms']]
Var_Dep = df_sydney['bathrooms']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[2919  324]
 [ 679  743]]
Precisión del modelo:
0.811284046692607
Precisión del modelo:
0.6963448922211809
Exactitud del modelo:
0.784994640943194
Sensibilidad del modelo:
0.9000925069380203
Sensibilidad del modelo:


***Modelo 9***

In [289]:
df_sydney.columns

Index(['bathrooms_numeric', 'maximum_nights_numeric',
       'reviews_per_month_numeric', 'host_total_listings_count_numeric',
       'price_numerico', 'Unnamed: 0', 'host_response_time',
       'host_acceptance_rate', 'property_type', 'room_type', 'amenities',
       'host_is_superhost', 'host_response_rate', 'host_acceptance_rate.1',
       'host_listings_count', 'host_total_listings_count', 'latitude',
       'longitude', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'revi

In [290]:
unico = np.unique(df_sydney["room_type"])
unico

array(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
      dtype=object)

In [294]:
df_sydney["room_type"]=df_sydney["room_type"].replace(['Hotel room', 'Entire home/apt'],"grupo1")
df_sydney["room_type"]=df_sydney["room_type"].replace(['Shared room',"Private room"],"grupo2")

In [295]:
unico = np.unique(df_sydney["room_type"])
unico

array(['grupo1', 'grupo2'], dtype=object)

In [296]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['price_numerico']]
Var_Dep = df_sydney['room_type']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo1")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="grupo2")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[4640    0]
 [  25    0]]
Precisión del modelo:
0.9946409431939979
Precisión del modelo:
0.0
Exactitud del modelo:
0.9946409431939979
Sensibilidad del modelo:
1.0
Sensibilidad del modelo:
0.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***Modelo 10***

In [303]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=df_sydney['review_scores_location'].max()
Min=df_sydney['review_scores_location'].min()
Limites= [Min, Max]
Limites

#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(3.94, 5.1, 3)
intervalos

#Creamos las categorías 
categorias= ["Alto", "Bajo"]

host_total_listings_count_numeric=df_sydney['review_scores_location']
df_sydney.insert(0,"review_scores_location_numeric", host_total_listings_count_numeric)

#Finalmente creamos las categorías en la columna numérica
df_sydney['review_scores_location']=pd.cut(x= df_sydney['review_scores_location'], bins=intervalos, labels= categorias )

df_sydney['review_scores_location'].head()

df_sydney["review_scores_location"].isnull().sum()

0

In [304]:
# Declaramos las variables dependientes e independientes para la regresión No lineal
Vars_Indep = df_sydney[['availability_30']]
Var_Dep = df_sydney['review_scores_location']

#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Precisión del modelo:')
print(precision)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Precisión del modelo:')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Alto")
print('Sensibilidad del modelo:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Bajo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Matriz de Confusión:
[[   0  434]
 [   0 4231]]
Precisión del modelo:
0.0
Precisión del modelo:
0.9069667738478028
Exactitud del modelo:
0.9069667738478028
Sensibilidad del modelo:
0.0
Sensibilidad del modelo:
1.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
